apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceName }}
  labels:
    {{- include "orientdb-helm.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.httpPort }}
    name: http
  - port: {{ .Values.binaryPort }}
    name: binary
  - port: {{ .Values.hazelcast.network.port }}
    name: hazelcast
  clusterIP: None
  selector:
    {{- include "orientdb-helm.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.statefulSetName }}
  labels:
    {{- include "orientdb-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "orientdb-helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.servers }}
  serviceName: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        {{- include "orientdb-helm.selectorLabels" . | nindent 8 }}
        {{ .Values.hazelcast.discovery.podLabel.name }}: {{ .Values.hazelcast.discovery.podLabel.value | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 30
      containers:
      - name: orientdb
        command: ["dserver.sh"]
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.httpPort }}
          protocol: TCP
        - containerPort: {{ .Values.binaryPort }}
          protocol: TCP
        - containerPort: {{ .Values.hazelcast.network.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {{ .Values.binaryPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.binaryPort }}
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
        volumeMounts:
        - name: databases
          mountPath: /orientdb/databases
        - name: config
          mountPath: /orientdb/config
        {{- if .Values.volumes.backup.mount }}
        - name: backup
          mountPath: /orientdb/backup
        {{- end }}
      # OrientDB needs the config files (at least server config) to be modifiable. Mounting directly from the configMap
      # would result in a read-only config folder which can crash the server.
      initContainers:
      - name: copy-configs
        image: busybox:1.31
        command: ['sh', '-c']
        args:
        - cp -v /orientdb-config/* /orientdb/config/
        volumeMounts:
        - name: config
          mountPath: /orientdb/config
        - name: orientdb-config-cm-vol
          mountPath: /orientdb-config
      volumes:
      - name: orientdb-config-cm-vol
        configMap:
          name: {{ .Values.orientdbConfigMapName }}
  volumeClaimTemplates:
  - metadata:
      name: databases
      {{- include "orientdb-helm.labels" . | nindent 6 }}
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.volumes.databases.storageClass }}
      resources:
        requests:
          storage: {{ .Values.volumes.databases.size }}
  - metadata:
      name: config
      {{- include "orientdb-helm.labels" . | nindent 6 }}
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.volumes.config.storageClass }}
      resources:
        requests:
          storage: {{ .Values.volumes.config.size }}
  {{- if .Values.volumes.backup.mount }}
  - metadata:
      name: backup
      {{- include "orientdb-helm.labels" . | nindent 6 }}
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.volumes.backup.storageClass }}
      resources:
        requests:
          storage: {{ .Values.volumes.backup.size }}
  {{- end }}